// appIndex
export const PJB_APP_INDEX_PAGE_BEGGING = 'PJB_APP_INDEX_PAGE_BEGGING'
export const PJB_APP_INDEX_PAGE_SUCCEED = 'PJB_APP_INDEX_PAGE_SUCCEED'
export const PJB_APP_INDEX_PAGE_FAILED = 'PJB_APP_INDEX_PAGE_FAILED'

// productList
export const PJB_PRODUCT_LIST_BEGGING = 'PJB_PRODUCT_LIST_BEGGING'
export const PJB_PRODUCT_LIST_SUCCEED = 'PJB_PRODUCT_LIST_SUCCEED'
export const PJB_PRODUCT_LIST_FAILED = 'PJB_PRODUCT_LIST_FAILED'